host: 0.0.0.0
port: 8001
log_dir: /app/data/BGL
out_dir: /app/data/BGL/out
dataset_file: /app/data/BGL/BGL.log
encoding: utf-8
tfidf:
  max_features: 20000
  ngram_range: [1, 2]
  min_df: 1
  max_df: 1.0

